### ISSUE TITLE
What’s the goal of this framework?

### ISSUE THREAD

**Issue by erlend-sh** [Noah2610/deathframe#1]
Hey 👋 

I’m from the Amethyst team and I’m just trying to figure out what your intention is for this project. Are you making a general purpose framework or will you be optimizing for a particular type of game/genre?

What does the framework do so far?

**Comment by Noah2610** [comment]
Hey @erlend-sh!

This is just an opinionated, 2D/platformer-focused framework for my personal game projects. There is no real goal for this crate, other than adding specific features to reduce my work-load for future projects.

It was originally created in preparation for Ludum Dare 44; our (unfinished) jam entry (and work-in-progress post-jam version) uses this framework: [LD44 repository](https://github.com/Noah2610/LD44), [LD44 Jam Entry](https://ldjam.com/events/ludum-dare/44/veggietartar)

This isn't something I would recommend for other people to use, as it's pretty opinionated and I haven't been taking too good care of it in regards to maintenance, code-quality, etc.
Although I've been writing some documentation, tests are lacking greatly... (no tests...)

In case you're interested, you should be able to build the documentation with `cargo doc --package deathframe` (the v0.0.0 build on docs.rs seems to have failed... I'll publish a new version soon, probably).

I'll write a proper README file soon, to maybe clarify some of the things I've written in this comment.

Some framework features:
- move entities with the `Velocity` component, using the `MoveEntitiesSystem`
- automatically decrease an entity's velocity with the `DecreaseVelocity` component and `DecreaseVelocitiesSystem`
- set a maximum velocity for an entity with `MaxVelocity` and `LimitVelocitiesSystem`
- gravity-affected entities with `Gravity` using the `GravitySystem`
- collision detection for `Solid` entities, so they cannot move into each other (also with `MoveEntitiesSystem`)
- general purpose collision detection with `Collision` and `CheckCollision` entities, using `CollisionSystem`; can be used by other systems to check collision states of entities
- automatic sprite scaling of entities with `amethyst::renderer::SpriteRender` and `ScaleOnce` (one-time) using the `ScaleSpritesSystem`
- `Animation` (single animation) and `AnimationsContainer` (multiple animations, switch from one animation to another) components with the `AnimationSystem` for simple sprite-by-sprite animations with delays
- a `Camera` wrapper component for `amethyst::renderer::Camera`, which can follow an entity
- a pretty terrible implementation of a background parallax effect with `Parallax` and `ParallaxSystem`

Anyways, thanks for working on Amethyst! I've been having a ton of fun with it!

**Comment by erlend-sh** [comment]
Neat! We have a conceptually similar project underway as an Amethyst showcase game: https://github.com/amethyst/space-menace

Maybe we’ll borrow some ideas from one another :)

**Comment by Noah2610** [comment]
The project looks really cool! I'll definitely borrow some of your ideas! :)
